const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Create Schema
const DocumentPermissionSchema = new Schema({
//should be auto generated by mongodb
dps_permission_id: {
type: String,
},
dps_customer_id: {
type: Schema.Types.ObjectId,
ref: "customers"
},
dps_service_provider_id: {
type: Schema.Types.ObjectId,
ref: "serviceProviders"
},
dps_document_id: {
type: Schema.Types.ObjectId,
ref: "customersuploaddocs"
},
dps_view_permission: {
type: String,
enum: ['yes', 'no'],
default: 'no'
},
dps_download_permission: {
type: String,
enum: ['yes', 'no'],
default: 'no'
},
dps_status: {
type: String,
enum: ['pending', 'accept', 'reject'],
default: 'pending'
},
dps_comment: { type: String },
dps_self_attested: {
type: String,
enum: ['yes', 'no'],
default: 'no'
},
dps_water_mark_added: {
type: String,
enum: ['yes', 'no'],
default: 'no'
},
dps_stamp: {
type: String,
enum: ['yes', 'no'],
default: 'no'
},
dps_created_at: {
type: Date,
default: Date.now
},
dps_updated_at: {
type: Date
},
dps_deleted_at: { type: Date },
dps_deleted: {
type: String,
enum: ['0', '1']
},
dps_is_active_user_flag: {
    type: String,
    enum: ['buyer', 'seller','renovator'],
    default: 'buyer'
  },
})
module.exports = docspermission = mongoose.model('docspermission', DocumentPermissionSchema);